{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discord-js-kuberscaler.fullname" . }}-manager
  labels:
    {{- include "discord-js-kuberscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "discord-js-kuberscaler.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "discord-js-kuberscaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
